### PR TITLE
chore: remove combine-spec step when generating code

### PR DESCRIPTION
**Pull request by ctreatma**
The OpenAPI generator is capable of generating code directly from the split API spec (in fact, that's how we were generating the combined spec, by running the openapi-yaml generator).  This removes the combine step from the Makefile and sync workflow in order to simplify the code generation process.

The only side effect of this change is that the openapi-yaml generator added values for some missing properties of the include and exclude parameters.  The properties added by openapi-yaml generator caused the include parameters to be added as `include=<a>&include=<b>`, whereas generating from the split spec causes include parameters to be added as `include=<a>,<b>`, which matches existing behavior in packngo.

### CODE REVIEW

**Comment by displague** [comment]
> include=<a>&include=<b>

I've verified that the API will NOT accept this format.

**Review by displague — APPROVED** [review]

**Comment by displague** [comment]
Did we need to remove the `spec/*combined` dir and revise the README? https://github.com/equinix-labs/metal-go#contents

**Comment by ctreatma** [comment]
Yep, missed that

**Comment by ctreatma** [comment]
Cleanup is in #103

**Pull request merged**
