### PR TITLE
fix: Added IPAssignments type

### PR DESCRIPTION
**Pull request by vasubabu**

### CODE REVIEW

**Comment by displague** [comment]
Does it make sense to introduce an IPAddress.type enum with value IPAssignment if that field doesn't really exist in the API?

We've discussed alternative approaches elsewhere. Some of the fields that would be involved are not included in the spec, but can be seen via `metal ip get -o yaml`. We can also see these fields were included in packngo: https://github.com/packethost/packngo/blob/master/ip.go#L56-L130

field|apparent purpose
---|---
addon | (not documented) appears to be true for all approved elastic IPs, false otherwise 
bill | not obvious if only or all reservations would have this as true, but also appears true for approved elastic IPs, false otherwise
state | reserved and non-reserved IPs will say "created" in their success state
requested_by | this field seems to have a User reference (href, id, short_id) with reservations, and is null (but present) otherwise

**Comment by ctreatma** [comment]
In terms of identifying that a particular JSON object is an IP reservation or a VRF IP reservation, that is already in place using the `type` enum as specified in the upstream spec, and I don't think we should change that; the case we are covering with this patch is how to identify that a  particular JSON object that _is_ an IP reservation (or a VRF IP reservation) is not _also_ an IP assignment.

The invalid `type` workaround was initially chosen because it lines up with how `IPReservation` and `VrfIPReservation` are differentiated.  By specifying an invalid value for type, we provide a way for the SDK to know that an `IPReservation` or `VrfIPReservation` is _not_ an `IPAssignment`, without making assumptions about the other properties that are defined for `IPAssignment`.  Since the `type` is optional, the JSON for an IP assignment will still match the patched spec; since the `type` value specified for `IPAssignment` is not a value the API will return, the JSON for an IP reservation or VRF IP reservation will not match the patched spec.

Requiring the `assigned_to` property in the `IPAssignment` schema instead would be more direct, so I'm on board with that.

**Review by ctreatma — APPROVED** [review]
@vasubabu I was going to ask if you had a chance to test with @displague's suggestion to mark `assigned_to` as `required`, but then I remembered that required field validation doesn't work in this SDK.

I created #159 to better track the required field issue (there was already a PR to experiment with implementing it, but having an issue for it will make it more visible).  Given that issue, I'm OK with keeping the `type` workaround you've implemented, but I'd like @displague to give a 👍 or 👎 before this gets merged.

**Comment by ctreatma** [comment]
I'll go ahead and merge this; it's already been tested in `metal-cli` and we don't have a viable alternative.  We can revisit after #159 is addressed.

**Pull request merged**
